### ISSUE TITLE
登陆界面 Request failed with status code 405

### ISSUE THREAD

**Issue by Blaine-White** [amerainc/rainc-job-vue#1]
你好，运行后，点击登陆出现Request failed with status code 405，自己尝试修改没有解决，可以请教一下吗？谢谢
<img width="451" alt="捕获" src="https://user-images.githubusercontent.com/69073023/165080409-76d35a2e-0f1d-4ec5-b476-91bf14aace16.PNG">

**Comment by amerainc** [comment]
你好已经修复了，刚毕业的时候做前端单点登录测试把测试代码给不小心带进去了
